config/routes.rb
RailsOrmHalloweenRuby003::Application.routes.draw do

  root 'welcome#index'

  resources :kids
  resources :buckets
  resources :houses
  resources :candies

end

app/models/bucket.rb
class Bucket < ActiveRecord::Base
  belongs_to :kid
  has_many :bucket_candies
  has_many :candies, :through => :bucket_candies

  def trick_or_treat(candy_object)
    self.candies ||= []
    self.candies << candy_object
  end

end

app/models/bucket_candy.rb
class BucketCandy < ActiveRecord::Base
  belongs_to :candy
  belongs_to :bucket

end

app/models/candy.rb
class Candy < ActiveRecord::Base
  has_many :bucket_candies
  has_many :house_candies
  has_many :buckets, :through => :bucket_candies
  has_many :houses, :through => :house_candies

  def self.find_candies(candy_ids)
    if !candy_ids.nil?
      candy_ids.collect do |candy_id|
          Candy.find(candy_id)
       end
    else
      []
    end
  end

end

app/models/house.rb
class House < ActiveRecord::Base
  has_many :house_candies
  has_many :candies, :through => :house_candies

  def self.give_candy(id)
    house = House.find(id)
    house.candies.shuffle.first
  end

end

app/models/house_candy.rb
class HouseCandy < ActiveRecord::Base
  belongs_to :candy
  belongs_to :house

end

app/models/kid.rb
class Kid < ActiveRecord::Base
  has_one :bucket
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController

  def show
    @bucket = Bucket.find(params[:id])
  end

  def update
    candy_object = House.give_candy(params[:house_id])
    @bucket = Bucket.find(params[:id])
    @bucket.trick_or_treat(candy_object)
    @bucket.save

    redirect_to (@bucket)
  end


# I want a link somewhere on the index of house page that links to Trick or Treat.
# When I click on that link, it should fire off a method that gets the kid's bucket.
# then that bucket should receive a random candy object that the house contains.
# The trick or treat method should then have something like this ||= []
# so that if there is no candies= yet, itll make an empty array
# then it will << the candy object into that kids bucket.

# the links should probably straight up call the update route of the buckets controller.
# Give candy can be a class method. first find the house from the link.

# probably in the house model

# I'll probably need some sort of show page to show the kid whats currently in his/her bucket from the index page


end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def index
    @kid = Kid.find(session[:user_id])
    @houses = House.all
  end

  def show
    @house = House.find(params[:id])
  end

  def new
    @house = House.new
    @candies = Candy.all
  end

  def edit
    @house = House.find(params[:id])
    @candies = Candy.all
  end

  def create
    candy_ids = params[:candies]
    candy_objects = Candy.find_candies(candy_ids)

    @house = House.new
    @house.name = params[:house][:name]
    @house.candies = candy_objects
    @house.save
    redirect_to(houses_path)
  end

  def update
    candy_ids = params[:candies]
    candy_objects = Candy.find_candies(candy_ids)

    @house = House.find(params[:id])
    @house.name = params[:house][:name]
    @house.candies = candy_objects
    @house.save
    redirect_to(house_path(@house))
  end


  def destroy
    @house.destroy
  end

  private
    def house_params
      params.require(:house).permit(:name)
    end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController

  def create
    # raise params.inspect
    k = Kid.find_or_create_by(:name => params[:kid][:name])
    k.bucket = Bucket.new
    k.save
    session[:user_id] = k.id

    redirect_to(houses_path)
  end

private
  def kid_params
    params.require(:kid).permit(:name, :age)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @kid = Kid.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/buckets/show.html.erb
<h3> The goods: </h3>

<ul>
<% @bucket.candies.each do |candy| %>
<li><%= candy.name %></li>
<% end %>
</ul>

<%= link_to "Back to Trick or Treatin'", houses_path %>

app/views/houses/edit.html.erb
<h3> Change it up: </h3>
<%= form_for @house do |f| %>
<%= f.text_field :name %>
<ul>
  <h4>Just don't give out pretzels...</h4>
  <% @candies.each do |candy| %>
        <%= label_tag candy.name %>
        <%= check_box_tag 'candies[]', candy.id,  @house.candies.include?(candy), :id => candy.name %>
        <br>
  <% end %>
</ul>
<%= f.submit %>
<% end %>

app/views/houses/index.html.erb
 <h2><%= @kid.name.titleize %>! Welcome to Elm Street</h2>
 <h3> Enjoy Trick or Treatin'</h3><br>


 <%= link_to "Check out yer haul", bucket_path(@kid.bucket) %><br>
 <br>


<h4> Take your pick of these fine houses: </h4>


<ul>
<% @houses.each do |house| %>
<li>

<%= link_to house.name, house %>
  <div>
    <%= form_tag("/buckets/#{@kid.bucket.id}", method: :put) %>
    <%= hidden_field_tag 'house_id', house.id %>
    <%= submit_tag "Trick or Treat!" %>
    </form>
  </div>
</li>
<br>
<% end %>
</ul>

<%= link_to "Visited all the Houses? Add another!", new_house_path %><br>

app/views/houses/new.html.erb
<h3> Add a new House! </h3>
<%= form_for @house do |f| %>
<%= f.text_field :name %>
<ul>
  <h4>Candies that this house gives out:</h4>
  <% @candies.each do |candy| %>
        <%= label_tag candy.name %>
        <%= check_box_tag 'candies[]', candy.id, false, :id => candy.name %>
        <br>
  <% end %>
</ul>
<%= f.submit %>
<% end %>

app/views/houses/show.html.erb
<h3><%= @house.name %></h3>

<h5>This house has these candies:</h5>
<ul>
<% @house.candies.each do |candy| %>
<li><%= candy.name %></li>
<% end %>
</ul>

<%= link_to "Tired of Hi-Chews? Run to the store and get something else.", edit_house_path(@house) %>

<br>
<br>
<%= link_to "Back to Trick or Treatin'", houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BOO!</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h3> 'Cause this is Thriller, Thriller Night.</h3>
<%= hidden_field_tag "Welcome to Halloween, the greatest holiday!" %>

<%= form_for(@kid) do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %></br>
  <%= f.label "Age" %>
  <%= f.number_field :age, in: 0..100 %></br>
  <%= f.submit "Start Trick Or Treatin'" %>
<% end %>